### ISSUE TITLE
Error: NodeJS 10.15.1 Module 64 not compatible

### ISSUE THREAD

**Issue by hoogw** [DenisCarriere/mbtiles-server#14]
I run and error: 

                     `C:\Users\engcid299\mbtiles-server>mbtiles-server --cache C:\Users\engcid299\mbtiles-server --verbose --port 7200
C:\Users\engcid299\AppData\Roaming\npm\node_modules\mbtiles-server\node_modules\sqlite3-offline-win32\index.js:21
  throw new Error(`NodeJS ${NODE} Module ${MODULES} not compatible`)
  ^

Error: NodeJS 10.15.1 Module 64 not compatible
    at Object.<anonymous> (C:\Users\engcid299\AppData\Roaming\npm\node_modules\mbtiles-server\node_modules\sqlite3-offline-win32\index.js:21:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\engcid299\AppData\Roaming\npm\node_modules\mbtiles-server\node_modules\sqlite3-offline\index.js:7:74)
    at Module._compile (internal/modules/cjs/loader.js:689:30)`

**Comment by richardeschloss** [comment]
Same issue for node:lts (docker image)

Error: NodeJS 18.16.1 Module 108 not compatible
    at Object.<anonymous> (/usr/local/lib/node_modules/mbtiles-server/node_modules/sqlite3-offline/binaries/index.js:21:9)

**Comment by richardeschloss** [comment]
I think this is fixed in later versions of node. Supported node versions:
https://www.npmjs.com/package/sqlite3-offline#supported-nodejs-release

Docker image here seems to work: https://hub.docker.com/r/deniscarriere/mbtiles-server (based on node 10.16.0)
