### ISSUE TITLE
Docker image crashes

### ISSUE THREAD

**Issue by endast** [DenisCarriere/mbtiles-server#4]
After buildning and running the docker file

```
$ docker build -t mbtiles-server .
$ docker run --rm -it \
  -p 5000:5000 \
  -v ~/mbtiles/:/root/mbtiles \
  mbtiles-server
```

The image crashes, it seems that **sqlite3-offline-linux** does not support node 9.2 included in the alipne-node image.

```

yarn run v1.3.2
$ node ./bin/mbtiles-server.js --verbose
/src/node_modules/sqlite3-offline-linux/index.js:21
  throw new Error(`NodeJS ${NODE} Module ${MODULES} not compatible`)
  ^

Error: NodeJS 9.2.0 Module 59 not compatible
    at Object.<anonymous> (/src/node_modules/sqlite3-offline-linux/index.js:21:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/node_modules/sqlite3-offline/index.js:5:74)
    at Module._compile (module.js:641:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by DenisCarriere** [comment]
Good catch 👍 

Might need to add the binary for  NodeJS 9 to [`sqlite3-offline`](https://github.com/DenisCarriere/sqlite3-offline):

https://github.com/DenisCarriere/sqlite3-offline
